services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: redis-cli ping | grep PONG
    ports:
    - 6379:6379
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
